### ISSUE TITLE
WNEAR-ETH pool id? 

### ISSUE THREAD

**Issue by alokc83** [jamesbachini/Aurora-Trisolaris-Auto-Compound-Script#1]
Hi James, 
I am following your tutorial. You took the example of the TRI-USDT pool. I have invested in WNEAR-ETH pool. 
I am very new for blockchain programming. I am not seeing the way to get pool id how you got here. It seems that the contract was verified. (https://jamesbachini.com/automate-yield-farming/)
<img width="835" alt="Screen Shot 2022-02-12 at 8 30 25 PM" src="https://user-images.githubusercontent.com/59144/153734452-91e314d7-183d-4bb6-9b27-ad74751ab36b.png">

This is my first harvesting tx: 
https://explorer.mainnet.aurora.dev/tx/0xb74f95439f2e0d15a37b1ab563bbca43070b11eccc8c44e32f4448d873306fc9/logs 

I see this in the input area: 
<img width="808" alt="Screen Shot 2022-02-12 at 8 31 40 PM" src="https://user-images.githubusercontent.com/59144/153734480-8fdd0e2e-ee97-4625-a434-a4eb91c0a77e.png">

Did you also see this or your contract was already verified. if you verified it yourself can you please give me some pointer? 

Thank you for putting this tutorial. I feel I am going to learn a lot from your tutorials. 
Please keep up the good work.

**Comment by jamesbachini** [comment]
If you scroll down to the very bottom of the page for that harvesting tx there is a field "pid = 0" this is the pool ID
